#!/bin/bash
# ==============================================================================
# Sync Environment Variables - Monorepo-Friendly .env Management
# ==============================================================================
# Merges root .env with project-specific .env.defaults
# Usage: ./scripts/sync-env.sh [project-name]
#        ./scripts/sync-env.sh --all
# ==============================================================================

set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_ENV="$ROOT_DIR/.env"

sync_project_env() {
    local PROJECT_NAME=$1
    local PROJECT_DIR="$ROOT_DIR/projects/$PROJECT_NAME"
    local PROJECT_ENV_DEFAULTS="$PROJECT_DIR/.env.defaults"
    local PROJECT_ENV="$PROJECT_DIR/.env"

    if [ ! -d "$PROJECT_DIR" ]; then
        echo -e "${YELLOW}⚠️  Project not found: $PROJECT_NAME${NC}"
        return 1
    fi

    echo -e "${BLUE}📦 Syncing env for: $PROJECT_NAME${NC}"

    # Create .env header
    cat > "$PROJECT_ENV" << EOF
# ==============================================================================
# $PROJECT_NAME - Environment Variables
# ==============================================================================
# Auto-generated by scripts/sync-env.sh
# DO NOT EDIT - Changes will be overwritten
# ==============================================================================

# ------------------------------------------------------------------------------
# Inherited from root .env
# ------------------------------------------------------------------------------
EOF

    # Copy relevant variables from root .env
    if [ -f "$ROOT_ENV" ]; then
        # Extract Spotify variables
        grep -E '^(VITE_)?SPOTIFY_' "$ROOT_ENV" | sed 's/^VITE_//' >> "$PROJECT_ENV" || true

        # Extract Google variables
        grep -E '^(VITE_)?GOOGLE_' "$ROOT_ENV" | sed 's/^VITE_//' >> "$PROJECT_ENV" || true

        # Extract Atlassian variables
        grep -E '^ATLASSIAN_' "$ROOT_ENV" >> "$PROJECT_ENV" || true
    fi

    # Add project-specific defaults if they exist
    if [ -f "$PROJECT_ENV_DEFAULTS" ]; then
        echo "" >> "$PROJECT_ENV"
        echo "# ------------------------------------------------------------------------------" >> "$PROJECT_ENV"
        echo "# Project-specific configuration" >> "$PROJECT_ENV"
        echo "# ------------------------------------------------------------------------------" >> "$PROJECT_ENV"
        cat "$PROJECT_ENV_DEFAULTS" >> "$PROJECT_ENV"
    fi

    echo -e "${GREEN}✓ Synced: $PROJECT_ENV${NC}"
}

# Main execution
if [ "$1" == "--all" ]; then
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║   Syncing Environment Variables for All Projects          ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    for PROJECT_DIR in "$ROOT_DIR"/projects/*/; do
        PROJECT_NAME=$(basename "$PROJECT_DIR")
        sync_project_env "$PROJECT_NAME"
    done
elif [ -n "$1" ]; then
    sync_project_env "$1"
else
    echo -e "${YELLOW}Usage:${NC}"
    echo -e "  $0 <project-name>    # Sync specific project"
    echo -e "  $0 --all             # Sync all projects"
    echo ""
    echo -e "${YELLOW}Examples:${NC}"
    echo -e "  $0 quantified-life"
    echo -e "  $0 --all"
    exit 1
fi

echo ""
echo -e "${GREEN}✓ Environment sync complete!${NC}"
